 
version: '3.3'

services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        volumes:
          - ./jenkins:/var/jenkins_home
        restart: always
        networks:
          itsccn_net:

networks:
    itsccn_net:
        external: true
